export const projectsData = [
	{
		id: 1,
		title: 'Belajar Dasar AI',
		url: 'google-health-platform',
		category: 'Dicoding',
		img: '/images/D9.png',
		link: 'https://www.dicoding.com/certificates/N9ZOYL5M6PG5',
	},
	{
		id: 2,
		title: 'Pemrograman dengan Dart',
		url: 'phoenix-digital-agency',
		category: 'Dicoding',
		img: '/images/D11.png',
		link: 'https://www.dicoding.com/certificates/GRX54Y2MKP0M',
	},
	{
		id: 3,
		title: 'Operator Komputer Madya',
		url: 'project-management-ui',
		category: 'BPPTIK Cikarang',
		img: '/images/vsga.png',
		link: 'https://drive.google.com/file/d/1lillUXC99qvdXyvQI8-HxxAqocD4Hh40/view?usp=sharing',
	},
	{
		id: 4,
		title: 'Operator Komputer Madya (VSGA)',
		url: 'cloud-storage-platform',
		category: 'BNSP, BPPTIK',
		img: '/images/vsga4.png',
		link: 'https://drive.google.com/file/d/1WOiExZKLH7soSdZgfARBjAb2w8ihoS5F/view?usp=drive_link',
	},
	{
		id: 5,
		title: 'Membangun Aplikasi Studi Kasus Directory Listing App',
		url: 'wetalk-social-app',
		category: 'Codepolitan',
		img: '/images/ls-app.png',
		link: 'https://codepolitan.com/c/WRTJ3LQ',
	},
	{
		id: 6,
		title: 'JavaScript Asynchronous',
		url: 'wetalk-social-app',
		category: 'Codepolitan',
		img: '/images/js-asy.png',
		link: 'https://codepolitan.com/c/TAGCOXS',
	},
	{
		id: 7,
		title: 'Auth dan Implementasi di Express.js',
		url: 'wetalk-social-app',
		category: 'Codepolitan',
		img: '/images/auth.png',
		link: 'https://codepolitan.com/c/HZDE0O9',
	},
	{
		id: 8,
		title: 'CSS',
		url: 'wetalk-social-app',
		category: 'Codepolitan',
		img: '/images/css.png',
		link: 'https://codepolitan.com/c/KSLBN3R',
	},
	{
		id: 9,
		title: 'Express.js',
		url: 'wetalk-social-app',
		category: 'Codepolitan',
		img: '/images/express.png',
		link: 'https://codepolitan.com/c/NSLEYOQ',
	},
	{
		id: 10,
		title: 'HTML',
		url: 'wetalk-social-app',
		category: 'Codepolitan',
		img: '/images/html.png',
		link: 'https://codepolitan.com/c/CY3PBXO',
	},
	{
		id: 11,
		title: 'Node.js dan NPM',
		url: 'wetalk-social-app',
		category: 'Codepolitan',
		img: '/images/nodejs.png',
		link: 'https://codepolitan.com/c/XWGK68J',
	},
	{
		id: 12,
		title: 'Vue.js',
		url: 'wetalk-social-app',
		category: 'Codepolitan',
		img: '/images/vue.png',
		link: 'https://codepolitan.com/c/W4XGQS6',
	},
	{
		id: 13,
		title: 'JavaScript DOM',
		url: 'wetalk-social-app',
		category: 'Codepolitan',
		img: '/images/js-dom.png',
		link: 'https://codepolitan.com/c/8NBD7AW',
	},
	{
		id: 14,
		title: 'JavaScript',
		url: 'wetalk-social-app',
		category: 'Codepolitan',
		img: '/images/js.png',
		link: 'https://codepolitan.com/c/PBAXEC6',
	},
	{
		id: 15,
		title: ' AJAX dan Web API',
		url: 'wetalk-social-app',
		category: 'Codepolitan',
		img: '/images/ajax.png',
		link: 'https://codepolitan.com/c/MZPMQ2D',
	},
	{
		id: 16,
		title: 'Bootstrap CSS Framework',
		url: 'wetalk-social-app',
		category: 'Codepolitan',
		img: '/images/b-css.png',
		link: 'https://codepolitan.com/c/FVT1HJO',
	},
	{
		id: 17,
		title: 'Web Dinamis dengan Express.js dan EJS',
		url: 'wetalk-social-app',
		category: 'Codepolitan',
		img: '/images/w-dinamis.png',
		link: 'https://codepolitan.com/c/K7NQMMS',
	},
	{
		id: 18,
		title: 'Project Express.js Dengan MongoDB',
		url: 'wetalk-social-app',
		category: 'Codepolitan',
		img: '/images/p-exp.png',
		link: 'https://codepolitan.com/c/GO5S3H0',
	},
	{
		id: 19,
		title: 'Relasi Data di MongoDB',
		url: 'wetalk-social-app',
		category: 'Codepolitan',
		img: '/images/mongo-db.png',
		link: 'https://codepolitan.com/c/FEKCSUN',
	},
	{
		id: 20,
		title: 'Nest.js',
		url: 'wetalk-social-app',
		category: 'Codepolitan',
		img: '/images/nest.png',
		link: 'https://codepolitan.com/c/0VKQGZ3',
	},
	{
		id: 21,
		title: 'Membangun RESTful dengan Adonis.js',
		url: 'wetalk-social-app',
		category: 'Codepolitan',
		img: '/images/adonis.png',
		link: 'https://codepolitan.com/c/D5GQU6S',
	},
	{
		id: 22,
		title: 'Error Handler di Express.js dan Mongoose',
		url: 'wetalk-social-app',
		category: 'Codepolitan',
		img: '/images/error.png',
		link: 'https://codepolitan.com/c/EKTCVOY',
	},
	{
		id: 23,
		title: 'MongoDB, Express, Vue, Node - Shopping Cart',
		url: 'wetalk-social-app',
		category: 'Codepolitan',
		img: '/images/sh-cd.png',
		link: 'https://codepolitan.com/c/JL0B32Y',
	},
	{
		id: 24,
		title: 'Hot Data dengan Session di Express.js',
		url: 'wetalk-social-app',
		category: 'Codepolitan',
		img: '/images/ss.png',
		link: 'https://codepolitan.com/c/HXKP3OT',
	},
	{
		id: 25,
		title: 'OOP',
		url: 'wetalk-social-app',
		category: 'Codepolitan',
		img: '/images/oop.png',
		link: 'https://codepolitan.com/c/96CIFGU',
	},
	{
		id: 26,
		title: 'MongoDB di JavaScript',
		url: 'wetalk-social-app',
		category: 'Codepolitan',
		img: '/images/mongo2.png',
		link: 'https://codepolitan.com/c/EQ7WYHL',
	},
	{
		id: 27,
		title: 'Implementasi Middleware pada Express.js',
		url: 'wetalk-social-app',
		category: 'Codepolitan',
		img: '/images/mdl.png',
		link: 'https://codepolitan.com/c/NBP13WY',
	},
	{
		id: 28,
		title: 'Relasi Database MongoDB di Express, Mongoose',
		url: 'wetalk-social-app',
		category: 'Codepolitan',
		img: '/images/mongo-exp.png',
		link: 'https://codepolitan.com/c/IVH5Y7F',
	},
	{
		id: 29,
		title: 'MongoDB',
		url: 'wetalk-social-app',
		category: 'Codepolitan',
		img: '/images/mongo.png',
		link: 'https://codepolitan.com/c/QREHLJZ',
	},
	{
		id: 30,
		title: 'RESTful dengan Express.js',
		url: 'wetalk-social-app',
		category: 'Codepolitan',
		img: '/images/restful.png',
		link: 'https://codepolitan.com/c/BZIWE4Y',
	},
	{
		id: 31,
		title: 'Manajemen Route dan Cookies di Express.js',
		url: 'wetalk-social-app',
		category: 'Codepolitan',
		img: '/images/ck.png',
		link: 'https://codepolitan.com/c/OXBBVSO',
	},
	{
		id: 32,
		title: 'Pemrograman dengan Haskell',
		url: 'wetalk-social-app',
		category: 'Dicoding',
		img: '/images/D8.png',
		link: 'https://www.dicoding.com/certificates/NVP78N76VXR0',
	},
	{
		id: 33,
		title: 'Dasar Pemrograman Pengembang Software',
		url: 'apple-new-design-system',
		category: 'Dicoding',
		img: '/images/D2.png',
		link: 'https://www.dicoding.com/certificates/JLX1W58DGP72',
	},
	{
		id: 35,
		title: 'Create a Cloud-based Blog with ECS',
		url: 'apple-new-design-system',
		category: 'Alibaba Cloud',
		img: '/images/ab3.png',
		link: 'https://alicloud-common.oss-ap-southeast-1.aliyuncs.com/2023/Developers/Certified-Developer.jpg',
	},
	{
		id: 36,
		title: 'Belajar Dasar Structured Query Language (SQL)',
		url: 'apple-new-design-system',
		category: 'Dicoding',
		img: '/images/D7.png',
		link: 'https://www.dicoding.com/certificates/2VX36OJQJXYQ',
	},
	{
		id: 37,
		title: 'Belajar Dasar Git dengan GitHub',
		url: 'apple-new-design-system',
		category: 'Dicoding',
		img: '/images/D5.png',
		link: 'https://www.dicoding.com/certificates/QLZ9R7OMEP5D',
	},
	{
		id: 38,
		title: 'Belajar Dasar-Dasar DevOps',
		url: 'apple-new-design-system',
		category: 'Dicoding',
		img: '/images/D6.png',
		link: 'https://www.dicoding.com/certificates/N9ZO43778ZG5',
	},
	{
		id: 39,
		title: 'Belajar Dasar Pemrograman Web',
		url: 'apple-new-design-system',
		category: 'Dicoding',
		img: '/images/D1.png',
		link: 'https://www.dicoding.com/certificates/EYX497KD6PDL',
	},
	{
		id: 40,
		title: 'Cloud Practitioner Essentials',
		url: 'apple-new-design-system',
		category: 'Dicoding',
		img: '/images/D3.png',
		link: 'https://www.dicoding.com/certificates/4EXG53D1DXRL',
	},
	{
		id: 41,
		title: 'Membuat Aplikasi Back-End untuk Pemula',
		url: 'apple-new-design-system',
		category: 'Dicoding',
		img: '/images/D4.png',
		link: 'https://www.dicoding.com/certificates/QLZ9K645DZ5D',
	},
	{
		id: 42,
		title: 'Belajar Dasar Pemrograman JavaScript',
		url: 'apple-new-design-system',
		category: 'Dicoding',
		img: '/images/D10.png',
		link: 'https://www.dicoding.com/certificates/4EXG5K5OQXRL',
	},
	{
		id: 43,
		title: 'Deploy MySQL Database in 10 Minutes',
		url: 'apple-new-design-system',
		category: 'Alibaba Cloud',
		img: '/images/ab1.png',
		link: 'https://drive.google.com/file/d/11n9QCYkUioCDg0tDf4TwBgqh51QSbGqe/view?usp=sharing',
	}
];
